name: Add pre and post publishing check list as comment
on:
  issues:
    types: [labeled]

jobs:
  add-comment:
    if: ${{ github.event.label.name == 'flow-ready to publish' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add pre and post publishing check list as comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: | 
                Pre-publishing checklist
                - [ ] Post Title and subheaders in sentence case

