name: Notify users based on roundup label
on: 
  issues:
    types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps: 
        - uses: jenschelkopf/issue-label-notification-action@1.3
          with:
            message: 'Heads-up {receipients}, to include news for developers, please add a commnet on this issue. Deadline 8th of next month'
            recipients: |
                Monthly Roundup=@bph
