name: Notify users based on roundup label
on: 
  issues:
    types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps: 
        - uses: jenschelkopf/issue-label-notification-action@1.3
          with:
            recipients: |
                Monthly Roundup=@bph
            message: 'Heads-up {receipients}: To include your news for developers, please add a comment on this issue. Deadline 8th of next month'
